version: '3.4'
services:
  db: # Nome do container de MySQL
    image: mysql:5.7.22 # FROM mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    env_file:
    - ./config/db.env         
    ports:
      - 3308:3306
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:latest # Carregando a imagem do wordpress na sua ultima versão
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
    # Acessando o banco
    # Configurando o wordpress para conectar com o DB (seguir o user, senha do mesmo de cima)
    env_file:
      - ./config/wp.env
    ports: 
      - 8000:80
    networks:
      - wordpress-network
networks:
    wordpress-network:
      driver: bridge

# sudo gpasswd -a $USER docker
# newgrp docker
